# Generated by Django 3.2.16 on 2022-12-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221214_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
