# Generated by Django 3.2.16 on 2022-12-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221216_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
